controllers:
  resource: ../../src/Endpoints
  type: attribute
  prefix: '/{_locale}/api'
  requirements:
    _locale: '%supported_locales_path%'

rest_controllers:
  resource: ../../src/Controller/Rest/
  type: attribute
  prefix: '/{_locale}'
  requirements:
    _locale: '%supported_locales_path%'

kernel:
  resource: ../../src/Kernel.php
  type: attribute