[program:cron]
command=cron -f -L 1
process_name=%(program_name)s
numprocs=1
autostart=true
autorestart=true
startsecs=1
startretries=10
exitcodes=0
stopsignal=TERM
stopwaitsecs=5
redirect_stderr=true
stdout_logfile=/var/log/supervisor/%(program_name)s_stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
stdout_capture_maxbytes=10MB
stderr_logfile=/var/log/supervisor/%(program_name)s_stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=10
stderr_capture_maxbytes=10MB
