[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
process_name=%(program_name)s
autostart=true
autorestart=true
startretries=10
numprocs=1
startsecs=1
stderr_logfile=/var/log/supervisor/%(program_name)s_stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=10
stderr_capture_maxbytes=10MB
stdout_logfile=/var/log/supervisor/%(program_name)s_stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
stdout_capture_maxbytes=10MB
