[program:php8-fpm]
command = /usr/local/sbin/php-fpm
process_name=%(program_name)s
autostart=true
autorestart=true
redirect_stderr=true
startsecs=1
stderr_logfile=/var/log/supervisor/%(program_name)s_stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=10
stderr_capture_maxbytes=10MB
stdout_logfile=/var/log/supervisor/%(program_name)s_stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
stdout_capture_maxbytes=10MB